# Generated by Django 5.2.6 on 2025-11-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioAsignado',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMusculo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('porcentaje', models.CharField(max_length=255)),
                ('idEjercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musculos.ejercicio')),
                ('idMusculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musculos.musculo')),
            ],
        ),
    ]
