# Generated by Django 5.2.6 on 2025-11-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMusculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.CharField(max_length=255)),
                ('idEjercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musculos.ejercicio')),
                ('idMusculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musculos.musculo')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musculos.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('idDetalleMusculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_asignados', to='musculos.detallemusculo')),
            ],
        ),
    ]
