# Generated by Django 5.2.6 on 2025-11-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='musculo',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
